### ISSUE TITLE
'dividE' Not working properly

### ISSUE THREAD

**Issue by Oshan-Dilmina** [Ashen-Dulmina/Brain-Rot#7]
When I try to use a simple 'dividE' syntax the compiled file gives out an error.
The 'dividE' syntax is directly implemented in the compiled file.
This is my code

`make x be 5 dividE 333333`

When I run the compiled file it gives out this error :

`
x = 5 dividE 333333
`
.............^^^^...............

it'd be skibidi if you fix this

**Comment by Ashen-Dulmina** [comment]
Hey, Oshan

We are grateful that you brought this bug to our attention.
The bug was caused by one of our spelling mistakes in the initial compiler code.
I'm happy to announce that I have fixed the mistake and updated the code in the newest vesion.
Please update to the new version and notify us whenever you have a problem

Thank you
