### ISSUE TITLE
Math operations doesn't work with 'freespeech'

### ISSUE THREAD

**Issue by Oshan-Dilmina** [Ashen-Dulmina/Brain-Rot#9]
Math operations (minuS,pluS,dividE,multiplY) does not work with freespeech

`freespeech|5 dividE 9`
 
error :

```
    print(5 dividE 9)
          ^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

**Comment by Ashen-Dulmina** [comment]
Hey again Oshan,

You get that error because we haven't implemented that yet.
Because the project is still being built through its early stages.

You could still use the 'dividE' through variables and print the variable itself 
Like this :

```
make var be 5 dividE 9
freespeech|var

```

But we will add this feature ASAP. 
Thank you for bringing this detail to our attention, 
We will notify you when this functionality is added.

**Comment by Ashen-Dulmina** [comment]
Hey Oshan,

We are happy to inform you that the feature you requested have been added
in the latest commit and the 'freespeech' command will be able to handle math.
Thank you for giving this suggestion.

Update to the new version and **START COOKING**
